language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION="4.2.*"
  - LARAVEL_VERSION="5.0.*"
  - LARAVEL_VERSION="5.4.*"
  - LARAVEL_VERSION="5.5.*"

matrix:
  exclude:
  - php: 5.5
    env: LARAVEL_VERSION="5.4.*"
  - php: 5.5
    env: LARAVEL_VERSION="5.5.*"
  - php: 5.6
    env: LARAVEL_VERSION="5.5.*"

before_script:
  - travis_retry composer self-update
  - travis_retry composer require laravel/framework:${LARAVEL_VERSION} --no-update
  - travis_retry composer require illuminate/support:${LARAVEL_VERSION} --no-update
  - travis_retry composer require illuminate/database:${LARAVEL_VERSION} --no-update
  - travis_retry composer install --prefer-source --no-interaction

script: phpunit
