language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - LARAVEL_VERSION="5.5.*"
  - LARAVEL_VERSION="5.8.*"
  - LARAVEL_VERSION="6.0.*"
  
# matrix:
#   exclude:
#   - php: 7.2
#     env: LARAVEL_VERSION="5.0.*"

before_script:
  - travis_retry composer self-update
  - travis_retry composer require laravel/framework:${LARAVEL_VERSION} --no-update
  - travis_retry composer require illuminate/support:${LARAVEL_VERSION} --no-update
  - travis_retry composer require illuminate/database:${LARAVEL_VERSION} --no-update
  - travis_retry composer install --prefer-source --no-interaction

script: phpunit
